// menu types
export const CHANGE_TO_SUMMARY = 'CHANGE_TO_SUMMARY';
export const CHANGE_TO_FEATURES = 'CHANGE_TO_FEATURES';
export const CHANGE_TO_STRATEGIES = 'CHANGE_TO_STRATEGIES';
export const CHANGE_TO_INSPIRATION = 'CHANGE_TO_INSPIRATION';
export const CHANGE_TO_BUSINESS_MODEL = 'CHANGE_TO_BUSINESS_MODEL';
export const CHANGE_TO_PLANNING = 'CHANGE_TO_PLANNING';
export const CHANGE_TO_RESOURCES = 'CHANGE_TO_RESOURCES';

// ideas types
export const ADD_IDEA = 'ADD_IDEA';
export const ADD_IDEA_DESCRIPTION = 'ADD_IDEA_DESCRIPTION';
export const DELETE_IDEA = 'DELETE_IDEA';
export const SET_IDEAS = 'SET_IDEAS';

export const FAVORITE_IDEA = 'FAVORITE_IDEA';
export const ARCHIVE_IDEA = 'ARCHIVE_IDEA';

// features types
export const ADD_FEATURE = 'ADD_FEATURE';
export const EDIT_FEATURE = 'EDIT_FEATURE';
export const DELETE_FEATURE = 'DELETE_FEATURE';
export const SET_FEATURES = 'SET_FEATURES';
export const UPDATE_FEATURES_AFTER_IDEA_DELETE =
  'UPDATE_FEATURES_AFTER_IDEA_DELETE';

// filters types
export const SORT_ALPHABETICALLY = 'SORT_ALPHABETICALLY';
export const SORT_BY_LAST_UPDATED = 'SORT_BY_LAST_UPDATED';
export const SORT_BY_LAST_CREATED = 'SORT_BY_LAST_CREATED';

export const RESET_VISIBILITY = 'RESET_VISIBILITY';
export const FILTER_FAVORITED = 'FILTER_FAVORITED';
export const FILTER_ARCHIVED = 'FILTER_ARCHIVED';

export const SET_FILTER_TEXT = 'SET_FILTER_TEXT';

// auth types
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';

// strategies types
export const ADD_STRATEGY = 'ADD_STRATEGY';
export const EDIT_STRATEGY = 'EDIT_STRATEGY';
export const DELETE_STRATEGY = 'DELETE_STRATEGY';
export const SET_STRATEGIES = 'SET_STRATEGIES';
export const UPDATE_STRATEGIES_AFTER_IDEA_DELETE =
  'UPDATE_STRATEGIES_AFTER_IDEA_DELETE';

// inspiration types
export const ADD_INSPIRATION = 'ADD_INSPIRATION';
export const EDIT_INSPIRATION = 'EDIT_INSPIRATION';
export const DELETE_INSPIRATION = 'DELETE_INSPIRATION';
export const SET_INSPIRATION = 'SET_INSPIRATION';
export const UPDATE_INSPIRATION_AFTER_IDEA_DELETE =
  'UPDATE_INSPIRATION_AFTER_IDEA_DELETE';
