// menu types
export const CHANGE_TO_SUMMARY = 'CHANGE_TO_SUMMARY'
export const CHANGE_TO_FEATURES = 'CHANGE_TO_FEATURES'
export const CHANGE_TO_STRATEGIES = 'CHANGE_TO_STRATEGIES'
export const CHANGE_TO_INSPIRATION = 'CHANGE_TO_INSPIRATION'
export const CHANGE_TO_BUSINESS_MODEL = 'CHANGE_TO_BUSINESS_MODEL'
export const CHANGE_TO_PLANNING = 'CHANGE_TO_PLANNING'
export const CHANGE_TO_RESOURCES = 'CHANGE_TO_RESOURCES'

// ideas types
export const ADD_IDEA = 'ADD_IDEA'
export const ADD_IDEA_DESCRIPTION = 'ADD_IDEA_DESCRIPTION'
export const DELETE_IDEA = 'DELETE_IDEA'
export const SET_IDEAS = 'SET_IDEAS'
export const SET_FEATURES = 'SET_FEATURES'

// features types
export const ADD_FEATURE = 'ADD_FEATURE'
export const EDIT_FEATURE = 'EDIT_FEATURE'
export const DELETE_FEATURE = 'DELETE_FEATURE'
export const UPDATE_FEATURES_AFTER_IDEA_DELETE = 'UPDATE_FEATURES_AFTER_IDEA_DELETE'

// filters types
export const SORT_BY_TITLE = 'SORT_BY_TITLE'
export const SORT_BY_LAST_EDITED = 'SORT_BY_LAST_EDITED'
export const SORT_BY_LAST_CREATED = 'SORT_BY_LAST_CREATED'
export const SET_FILTER_TEXT = 'SET_FILTER_TEXT'